### ISSUE TITLE
Implement a notfications methods

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lmtest#8]
Email maybe?

**Comment by maxxxxxdlp** [comment]
Webhooks would be nice too for more advanced users and they shouldn't be too hard to implement. Basically, users subscribe to log/error message for some/all tests. Then, if an error has occurred, lm_test would send a json or blob to the URL specified in the hook. The URL can be either remote or a localhost.
If needed, a webhook can be made to ping a local web server that in turn is connected to an email server.
I also used them to integrate with an arduino board to provide a physical alarm clock for when something went wrong xD

**Comment by cjgrady** [comment]
Hmm, webhooks are an interesting option but I wonder if that adds too much complexity for the first version.  I can absolutely see the utility, especially when doing something like setting a server status.  Let me think about it a bit.
